import { MigrationInterface, QueryRunner } from "typeorm";

export class IDIndex1672677779191 implements MigrationInterface {
    name = 'IDIndex1672677779191'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP CONSTRAINT "FK_5c5d83c09fef194ef807fc1273a"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP CONSTRAINT "FK_816d3059ea387d08879713c7316"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP CONSTRAINT "FK_a9c05100cb3647a5660d1c4c20d"`);
        await queryRunner.query(`CREATE TYPE "public"."quantity_comparator_enum" AS ENUM('<', '<=', '>=', '>', '')`);
        await queryRunner.query(`CREATE TABLE "quantity" ("id" SERIAL NOT NULL, "value" double precision, "comparator" "public"."quantity_comparator_enum" NOT NULL DEFAULT '', "unit" character varying, "system" character varying, "code" character varying, CONSTRAINT "PK_983c8c3c14b19e9cd69411cd946" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."observation_identifier_use_enum" AS ENUM('usual', 'official', 'temp', 'secondary', 'old')`);
        await queryRunner.query(`CREATE TABLE "observation_identifier" ("id" SERIAL NOT NULL, "use" "public"."observation_identifier_use_enum" NOT NULL DEFAULT 'official', "system" character varying, "value" character varying, "assigner" character varying, "periodId" integer, "observationId" integer, CONSTRAINT "REL_0d0493603d9db19e05d1833602" UNIQUE ("periodId"), CONSTRAINT "PK_00cbe1ec646e6dda12372596797" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ceb834d929b8588bc5f974a7df" ON "observation_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE TYPE "public"."observation_status_enum" AS ENUM('registered', 'preliminary', 'final', 'amended')`);
        await queryRunner.query(`CREATE TABLE "observation" ("id" SERIAL NOT NULL, "valueInteger" integer, "valueString" character varying, "status" "public"."observation_status_enum" NOT NULL DEFAULT 'final', "effectiveDateTime" TIMESTAMP NOT NULL DEFAULT '1900-01-01', "valueQuantityId" integer, "codeId" integer, "patientId" integer, "bodySiteId" integer, "methodId" integer, CONSTRAINT "REL_507bfa3364b78c67db103fe886" UNIQUE ("valueQuantityId"), CONSTRAINT "REL_d8a883d6442c4cf05f2f66c875" UNIQUE ("codeId"), CONSTRAINT "REL_1669d70141539fb74d73dda3cd" UNIQUE ("bodySiteId"), CONSTRAINT "REL_230847c56410cffb5a700bc233" UNIQUE ("methodId"), CONSTRAINT "PK_77a736edc631a400b788ce302cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "observation_category_codeable_concept" ("observationId" integer NOT NULL, "codeableConceptId" integer NOT NULL, CONSTRAINT "PK_365df30bd7d28fce4243f8f61cc" PRIMARY KEY ("observationId", "codeableConceptId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8fcc2a2bf2d5a0c142a88d5084" ON "observation_category_codeable_concept" ("observationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eaf132ff7a3fbe9b127020d6e8" ON "observation_category_codeable_concept" ("codeableConceptId") `);
        await queryRunner.query(`CREATE TABLE "observation_performer_practitioner" ("observationId" integer NOT NULL, "practitionerId" integer NOT NULL, CONSTRAINT "PK_5b5e7ceea181da587c9a414c0b3" PRIMARY KEY ("observationId", "practitionerId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5a58fa39db17f897e75e009546" ON "observation_performer_practitioner" ("observationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ee92e8b8b9fdc4c60cf6d5ae9" ON "observation_performer_practitioner" ("practitionerId") `);
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP CONSTRAINT "UQ_5c5d83c09fef194ef807fc1273a"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP COLUMN "conditionId"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP COLUMN "subjectId"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP COLUMN "patientId"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "offsetFromUTC"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "valueAtUTC"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "original"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD "conditionId" integer`);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD CONSTRAINT "UQ_5c5d83c09fef194ef807fc1273a" UNIQUE ("conditionId")`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD "patientId" integer`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD "subjectId" integer`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "original" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "value" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "offsetFromUTC" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "valueAtUTC" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        //await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        //await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        //await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_750a348c49aae2866fdd08efbe" ON "identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2bb6640ba6d3f27865b755873b" ON "appointment_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0cf84538504110d60bd43bf814" ON "encounter_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7e6ca88c465709b8b77c69f125" ON "patient_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9fb6a84f8a0b0e80931c4c1d7c" ON "qualification_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1ae0b84abc42f9f6c5d80cd2d7" ON "practitioner_identifier" ("system", "value") `);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD CONSTRAINT "FK_5c5d83c09fef194ef807fc1273a" FOREIGN KEY ("conditionId") REFERENCES "condition"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD CONSTRAINT "FK_a9c05100cb3647a5660d1c4c20d" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD CONSTRAINT "FK_816d3059ea387d08879713c7316" FOREIGN KEY ("subjectId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "observation_identifier" ADD CONSTRAINT "FK_0d0493603d9db19e05d1833602d" FOREIGN KEY ("periodId") REFERENCES "period"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "observation_identifier" ADD CONSTRAINT "FK_e4ff5a2030916d65ddbd80b7bd1" FOREIGN KEY ("observationId") REFERENCES "observation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "observation" ADD CONSTRAINT "FK_507bfa3364b78c67db103fe8862" FOREIGN KEY ("valueQuantityId") REFERENCES "quantity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "observation" ADD CONSTRAINT "FK_d8a883d6442c4cf05f2f66c8758" FOREIGN KEY ("codeId") REFERENCES "codeable_concept"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "observation" ADD CONSTRAINT "FK_12a252651b31de19badfbadd3e2" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "observation" ADD CONSTRAINT "FK_1669d70141539fb74d73dda3cdc" FOREIGN KEY ("bodySiteId") REFERENCES "codeable_concept"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "observation" ADD CONSTRAINT "FK_230847c56410cffb5a700bc233a" FOREIGN KEY ("methodId") REFERENCES "codeable_concept"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "observation_category_codeable_concept" ADD CONSTRAINT "FK_8fcc2a2bf2d5a0c142a88d5084a" FOREIGN KEY ("observationId") REFERENCES "observation"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "observation_category_codeable_concept" ADD CONSTRAINT "FK_eaf132ff7a3fbe9b127020d6e80" FOREIGN KEY ("codeableConceptId") REFERENCES "codeable_concept"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "observation_performer_practitioner" ADD CONSTRAINT "FK_5a58fa39db17f897e75e0095461" FOREIGN KEY ("observationId") REFERENCES "observation"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "observation_performer_practitioner" ADD CONSTRAINT "FK_0ee92e8b8b9fdc4c60cf6d5ae96" FOREIGN KEY ("practitionerId") REFERENCES "practitioner"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "observation_performer_practitioner" DROP CONSTRAINT "FK_0ee92e8b8b9fdc4c60cf6d5ae96"`);
        await queryRunner.query(`ALTER TABLE "observation_performer_practitioner" DROP CONSTRAINT "FK_5a58fa39db17f897e75e0095461"`);
        await queryRunner.query(`ALTER TABLE "observation_category_codeable_concept" DROP CONSTRAINT "FK_eaf132ff7a3fbe9b127020d6e80"`);
        await queryRunner.query(`ALTER TABLE "observation_category_codeable_concept" DROP CONSTRAINT "FK_8fcc2a2bf2d5a0c142a88d5084a"`);
        await queryRunner.query(`ALTER TABLE "observation" DROP CONSTRAINT "FK_230847c56410cffb5a700bc233a"`);
        await queryRunner.query(`ALTER TABLE "observation" DROP CONSTRAINT "FK_1669d70141539fb74d73dda3cdc"`);
        await queryRunner.query(`ALTER TABLE "observation" DROP CONSTRAINT "FK_12a252651b31de19badfbadd3e2"`);
        await queryRunner.query(`ALTER TABLE "observation" DROP CONSTRAINT "FK_d8a883d6442c4cf05f2f66c8758"`);
        await queryRunner.query(`ALTER TABLE "observation" DROP CONSTRAINT "FK_507bfa3364b78c67db103fe8862"`);
        await queryRunner.query(`ALTER TABLE "observation_identifier" DROP CONSTRAINT "FK_e4ff5a2030916d65ddbd80b7bd1"`);
        await queryRunner.query(`ALTER TABLE "observation_identifier" DROP CONSTRAINT "FK_0d0493603d9db19e05d1833602d"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP CONSTRAINT "FK_816d3059ea387d08879713c7316"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP CONSTRAINT "FK_a9c05100cb3647a5660d1c4c20d"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP CONSTRAINT "FK_5c5d83c09fef194ef807fc1273a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ae0b84abc42f9f6c5d80cd2d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fb6a84f8a0b0e80931c4c1d7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e6ca88c465709b8b77c69f125"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cf84538504110d60bd43bf814"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bb6640ba6d3f27865b755873b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_750a348c49aae2866fdd08efbe"`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "valueAtUTC"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "offsetFromUTC"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "original"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP COLUMN "subjectId"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP COLUMN "patientId"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP CONSTRAINT "UQ_5c5d83c09fef194ef807fc1273a"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP COLUMN "conditionId"`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "original" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "value" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "valueAtUTC" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "offsetFromUTC" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD "patientId" integer`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD "subjectId" integer`);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD "conditionId" integer`);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD CONSTRAINT "UQ_5c5d83c09fef194ef807fc1273a" UNIQUE ("conditionId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ee92e8b8b9fdc4c60cf6d5ae9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a58fa39db17f897e75e009546"`);
        await queryRunner.query(`DROP TABLE "observation_performer_practitioner"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eaf132ff7a3fbe9b127020d6e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fcc2a2bf2d5a0c142a88d5084"`);
        await queryRunner.query(`DROP TABLE "observation_category_codeable_concept"`);
        await queryRunner.query(`DROP TABLE "observation"`);
        await queryRunner.query(`DROP TYPE "public"."observation_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ceb834d929b8588bc5f974a7df"`);
        await queryRunner.query(`DROP TABLE "observation_identifier"`);
        await queryRunner.query(`DROP TYPE "public"."observation_identifier_use_enum"`);
        await queryRunner.query(`DROP TABLE "quantity"`);
        await queryRunner.query(`DROP TYPE "public"."quantity_comparator_enum"`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD CONSTRAINT "FK_a9c05100cb3647a5660d1c4c20d" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD CONSTRAINT "FK_816d3059ea387d08879713c7316" FOREIGN KEY ("subjectId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD CONSTRAINT "FK_5c5d83c09fef194ef807fc1273a" FOREIGN KEY ("conditionId") REFERENCES "condition"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
