import { MigrationInterface, QueryRunner } from "typeorm";

export class Newest1693954160205 implements MigrationInterface {
    name = 'Newest1693954160205'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "patient_name" DROP CONSTRAINT "FK_8d1b60aefc150fdd6c89d05eb4e"`);
        await queryRunner.query(`ALTER TABLE "patient_contact_point" DROP CONSTRAINT "FK_d27a1a70421e51e5b93f292c118"`);
        await queryRunner.query(`ALTER TABLE "patient_address" DROP CONSTRAINT "FK_971744b316662409103fa145f87"`);
        await queryRunner.query(`ALTER TABLE "patient_identifier" DROP CONSTRAINT "FK_933bf102d92916ab3f97c9878d2"`);
        await queryRunner.query(`ALTER TABLE "patient_communication" DROP CONSTRAINT "FK_7027a305efdef9c31ed79c3c912"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP CONSTRAINT "FK_a9c05100cb3647a5660d1c4c20d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e6ca88c465709b8b77c69f125"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_750a348c49aae2866fdd08efbe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fb6a84f8a0b0e80931c4c1d7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ae0b84abc42f9f6c5d80cd2d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cf84538504110d60bd43bf814"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bb6640ba6d3f27865b755873b"`);
        await queryRunner.query(`ALTER TABLE "encounter" RENAME COLUMN "patientId" TO "subjectId"`);
        await queryRunner.query(`ALTER TABLE "encounter" RENAME COLUMN "subjectId" TO "patientId"`);
        await queryRunner.query(`CREATE TYPE "public"."person_name_use_enum" AS ENUM('usual', 'official', 'temp', 'nickname', 'anonymous', 'old', 'maiden')`);
        await queryRunner.query(`CREATE TABLE "person_name" ("id" SERIAL NOT NULL, "use" "public"."person_name_use_enum" NOT NULL DEFAULT 'official', "text" character varying, "family" character varying, "given" text array, "prefix" character varying, "suffix" character varying, "periodId" integer, "personId" integer, CONSTRAINT "REL_16e79a61e414a664a6b8137fee" UNIQUE ("periodId"), CONSTRAINT "PK_dd16717b31bc32cf24d1f68974b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."person_contact_point_use_enum" AS ENUM('home', 'work', 'temp', 'old', 'mobile')`);
        await queryRunner.query(`CREATE TABLE "person_contact_point" ("id" SERIAL NOT NULL, "system" character varying, "value" character varying, "use" "public"."person_contact_point_use_enum" NOT NULL DEFAULT 'work', "rank" integer, "periodId" integer, "personId" integer, CONSTRAINT "REL_67641f3950aa9d766ef28b7bbc" UNIQUE ("periodId"), CONSTRAINT "PK_4327acac001bbcd8489ccaf3009" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."person_identifier_use_enum" AS ENUM('usual', 'official', 'temp', 'secondary', 'old')`);
        await queryRunner.query(`CREATE TABLE "person_identifier" ("id" SERIAL NOT NULL, "use" "public"."person_identifier_use_enum" NOT NULL DEFAULT 'official', "system" character varying, "value" character varying, "assigner" character varying, "periodId" integer, "personId" integer, CONSTRAINT "REL_0e2ece5150ca6edec64b10ce3d" UNIQUE ("periodId"), CONSTRAINT "PK_c730cbe37eb205520bcfbbd171d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d197dfdf413948ee6ae0f2e692" ON "person_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE TABLE "person_communication" ("id" SERIAL NOT NULL, "preferred" boolean, "languageId" integer, "personId" integer, CONSTRAINT "REL_69e73793f4a37bfc23d7e19eaf" UNIQUE ("languageId"), CONSTRAINT "PK_354834222f6d4a22439aae03f97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."person_gender_enum" AS ENUM('male', 'female', 'other', 'unknown')`);
        await queryRunner.query(`CREATE TABLE "person" ("id" SERIAL NOT NULL, "resourceType" character varying NOT NULL, "gender" "public"."person_gender_enum" NOT NULL DEFAULT 'unknown', "birthDate" date NOT NULL DEFAULT '1900-01-01', CONSTRAINT "PK_5fdaf670315c4b7e70cce85daa3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."person_address_use_enum" AS ENUM('home', 'work', 'temp', 'old', 'billing')`);
        await queryRunner.query(`CREATE TYPE "public"."person_address_type_enum" AS ENUM('postal', 'physical', 'both')`);
        await queryRunner.query(`CREATE TABLE "person_address" ("id" SERIAL NOT NULL, "use" "public"."person_address_use_enum" NOT NULL DEFAULT 'home', "type" "public"."person_address_type_enum" NOT NULL DEFAULT 'both', "text" character varying, "line" text array, "city" character varying, "district" character varying, "state" character varying, "postalCode" character varying, "country" character varying, "periodId" integer, "personId" integer, CONSTRAINT "REL_ce7981ecff7822fd9a76da806c" UNIQUE ("periodId"), CONSTRAINT "PK_cd587348ca3fec07931de208299" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "person_extension_extension" ("personId" integer NOT NULL, "extensionId" integer NOT NULL, CONSTRAINT "PK_0ad10696184181eb167762ed178" PRIMARY KEY ("personId", "extensionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7204a2f5d37e7a7aaf02d702c5" ON "person_extension_extension" ("personId") `);
        await queryRunner.query(`CREATE INDEX "IDX_82439417274b9dc2ccb09bbad3" ON "person_extension_extension" ("extensionId") `);
        await queryRunner.query(`CREATE TABLE "person_modifier_extension_extension" ("personId" integer NOT NULL, "extensionId" integer NOT NULL, CONSTRAINT "PK_4d7ca2757fdd535e2f775eb77cc" PRIMARY KEY ("personId", "extensionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a9d285c31cadcace3636e4aa1c" ON "person_modifier_extension_extension" ("personId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ead5c93ff9789623654a06303" ON "person_modifier_extension_extension" ("extensionId") `);
        await queryRunner.query(`ALTER TABLE "encounter" DROP COLUMN "patientId"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "offsetFromUTC"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "valueAtUTC"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "original"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD "conditionId" integer`);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD CONSTRAINT "UQ_5c5d83c09fef194ef807fc1273a" UNIQUE ("conditionId")`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD "patientId" integer`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD "subjectId" integer`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "original" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "value" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "offsetFromUTC" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "valueAtUTC" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "observation" ALTER COLUMN "effectiveDateTime" SET DEFAULT '1900-01-01'`);
        await queryRunner.query(`ALTER TABLE "observation" ALTER COLUMN "effectiveDateTime" SET DEFAULT '1900-01-01'`);
        await queryRunner.query(`ALTER TABLE "observation" ALTER COLUMN "effectiveDateTime" SET DEFAULT '1900-01-01'`);
        await queryRunner.query(`ALTER TABLE "observation" ALTER COLUMN "effectiveDateTime" SET DEFAULT '1900-01-01'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_750a348c49aae2866fdd08efbe" ON "identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2bb6640ba6d3f27865b755873b" ON "appointment_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0cf84538504110d60bd43bf814" ON "encounter_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7e6ca88c465709b8b77c69f125" ON "patient_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9fb6a84f8a0b0e80931c4c1d7c" ON "qualification_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1ae0b84abc42f9f6c5d80cd2d7" ON "practitioner_identifier" ("system", "value") `);
        await queryRunner.query(`ALTER TABLE "patient_name" ADD CONSTRAINT "FK_8d1b60aefc150fdd6c89d05eb4e" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_contact_point" ADD CONSTRAINT "FK_d27a1a70421e51e5b93f292c118" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_address" ADD CONSTRAINT "FK_971744b316662409103fa145f87" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_identifier" ADD CONSTRAINT "FK_933bf102d92916ab3f97c9878d2" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_communication" ADD CONSTRAINT "FK_7027a305efdef9c31ed79c3c912" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD CONSTRAINT "FK_5c5d83c09fef194ef807fc1273a" FOREIGN KEY ("conditionId") REFERENCES "condition"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD CONSTRAINT "FK_a9c05100cb3647a5660d1c4c20d" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD CONSTRAINT "FK_816d3059ea387d08879713c7316" FOREIGN KEY ("subjectId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_name" ADD CONSTRAINT "FK_16e79a61e414a664a6b8137fee0" FOREIGN KEY ("periodId") REFERENCES "period"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_name" ADD CONSTRAINT "FK_08e433dbcf284bce6185afa0b50" FOREIGN KEY ("personId") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_contact_point" ADD CONSTRAINT "FK_67641f3950aa9d766ef28b7bbc9" FOREIGN KEY ("periodId") REFERENCES "period"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_contact_point" ADD CONSTRAINT "FK_6a9f21ce05da38bb997e41a5269" FOREIGN KEY ("personId") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_identifier" ADD CONSTRAINT "FK_0e2ece5150ca6edec64b10ce3dd" FOREIGN KEY ("periodId") REFERENCES "period"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_identifier" ADD CONSTRAINT "FK_fdf541ce2d9aa80a6414d44ac49" FOREIGN KEY ("personId") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_communication" ADD CONSTRAINT "FK_69e73793f4a37bfc23d7e19eaf9" FOREIGN KEY ("languageId") REFERENCES "codeable_concept"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_communication" ADD CONSTRAINT "FK_a5e02a45d43a4ff63a049a2d764" FOREIGN KEY ("personId") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_address" ADD CONSTRAINT "FK_ce7981ecff7822fd9a76da806c0" FOREIGN KEY ("periodId") REFERENCES "period"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_address" ADD CONSTRAINT "FK_f79a1d5a864499940a8ecf95f83" FOREIGN KEY ("personId") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_extension_extension" ADD CONSTRAINT "FK_7204a2f5d37e7a7aaf02d702c56" FOREIGN KEY ("personId") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "person_extension_extension" ADD CONSTRAINT "FK_82439417274b9dc2ccb09bbad33" FOREIGN KEY ("extensionId") REFERENCES "extension"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "person_modifier_extension_extension" ADD CONSTRAINT "FK_a9d285c31cadcace3636e4aa1cc" FOREIGN KEY ("personId") REFERENCES "person"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "person_modifier_extension_extension" ADD CONSTRAINT "FK_4ead5c93ff9789623654a063036" FOREIGN KEY ("extensionId") REFERENCES "extension"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "person_modifier_extension_extension" DROP CONSTRAINT "FK_4ead5c93ff9789623654a063036"`);
        await queryRunner.query(`ALTER TABLE "person_modifier_extension_extension" DROP CONSTRAINT "FK_a9d285c31cadcace3636e4aa1cc"`);
        await queryRunner.query(`ALTER TABLE "person_extension_extension" DROP CONSTRAINT "FK_82439417274b9dc2ccb09bbad33"`);
        await queryRunner.query(`ALTER TABLE "person_extension_extension" DROP CONSTRAINT "FK_7204a2f5d37e7a7aaf02d702c56"`);
        await queryRunner.query(`ALTER TABLE "person_address" DROP CONSTRAINT "FK_f79a1d5a864499940a8ecf95f83"`);
        await queryRunner.query(`ALTER TABLE "person_address" DROP CONSTRAINT "FK_ce7981ecff7822fd9a76da806c0"`);
        await queryRunner.query(`ALTER TABLE "person_communication" DROP CONSTRAINT "FK_a5e02a45d43a4ff63a049a2d764"`);
        await queryRunner.query(`ALTER TABLE "person_communication" DROP CONSTRAINT "FK_69e73793f4a37bfc23d7e19eaf9"`);
        await queryRunner.query(`ALTER TABLE "person_identifier" DROP CONSTRAINT "FK_fdf541ce2d9aa80a6414d44ac49"`);
        await queryRunner.query(`ALTER TABLE "person_identifier" DROP CONSTRAINT "FK_0e2ece5150ca6edec64b10ce3dd"`);
        await queryRunner.query(`ALTER TABLE "person_contact_point" DROP CONSTRAINT "FK_6a9f21ce05da38bb997e41a5269"`);
        await queryRunner.query(`ALTER TABLE "person_contact_point" DROP CONSTRAINT "FK_67641f3950aa9d766ef28b7bbc9"`);
        await queryRunner.query(`ALTER TABLE "person_name" DROP CONSTRAINT "FK_08e433dbcf284bce6185afa0b50"`);
        await queryRunner.query(`ALTER TABLE "person_name" DROP CONSTRAINT "FK_16e79a61e414a664a6b8137fee0"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP CONSTRAINT "FK_816d3059ea387d08879713c7316"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP CONSTRAINT "FK_a9c05100cb3647a5660d1c4c20d"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP CONSTRAINT "FK_5c5d83c09fef194ef807fc1273a"`);
        await queryRunner.query(`ALTER TABLE "patient_communication" DROP CONSTRAINT "FK_7027a305efdef9c31ed79c3c912"`);
        await queryRunner.query(`ALTER TABLE "patient_identifier" DROP CONSTRAINT "FK_933bf102d92916ab3f97c9878d2"`);
        await queryRunner.query(`ALTER TABLE "patient_address" DROP CONSTRAINT "FK_971744b316662409103fa145f87"`);
        await queryRunner.query(`ALTER TABLE "patient_contact_point" DROP CONSTRAINT "FK_d27a1a70421e51e5b93f292c118"`);
        await queryRunner.query(`ALTER TABLE "patient_name" DROP CONSTRAINT "FK_8d1b60aefc150fdd6c89d05eb4e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ae0b84abc42f9f6c5d80cd2d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fb6a84f8a0b0e80931c4c1d7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e6ca88c465709b8b77c69f125"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cf84538504110d60bd43bf814"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bb6640ba6d3f27865b755873b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_750a348c49aae2866fdd08efbe"`);
        await queryRunner.query(`ALTER TABLE "observation" ALTER COLUMN "effectiveDateTime" SET DEFAULT '1900-01-01 00:00:00'`);
        await queryRunner.query(`ALTER TABLE "observation" ALTER COLUMN "effectiveDateTime" SET DEFAULT '1900-01-01 00:00:00'`);
        await queryRunner.query(`ALTER TABLE "observation" ALTER COLUMN "effectiveDateTime" SET DEFAULT '1900-01-01 00:00:00'`);
        await queryRunner.query(`ALTER TABLE "observation" ALTER COLUMN "effectiveDateTime" SET DEFAULT '1900-01-01 00:00:00'`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "practitioner" ALTER COLUMN "active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "valueAtUTC"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "offsetFromUTC"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "instant" DROP COLUMN "original"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP COLUMN "subjectId"`);
        await queryRunner.query(`ALTER TABLE "encounter" DROP COLUMN "patientId"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP CONSTRAINT "UQ_5c5d83c09fef194ef807fc1273a"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP COLUMN "conditionId"`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "original" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "value" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "valueAtUTC" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "instant" ADD "offsetFromUTC" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "encounter" ADD "patientId" integer`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ead5c93ff9789623654a06303"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9d285c31cadcace3636e4aa1c"`);
        await queryRunner.query(`DROP TABLE "person_modifier_extension_extension"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82439417274b9dc2ccb09bbad3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7204a2f5d37e7a7aaf02d702c5"`);
        await queryRunner.query(`DROP TABLE "person_extension_extension"`);
        await queryRunner.query(`DROP TABLE "person_address"`);
        await queryRunner.query(`DROP TYPE "public"."person_address_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."person_address_use_enum"`);
        await queryRunner.query(`DROP TABLE "person"`);
        await queryRunner.query(`DROP TYPE "public"."person_gender_enum"`);
        await queryRunner.query(`DROP TABLE "person_communication"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d197dfdf413948ee6ae0f2e692"`);
        await queryRunner.query(`DROP TABLE "person_identifier"`);
        await queryRunner.query(`DROP TYPE "public"."person_identifier_use_enum"`);
        await queryRunner.query(`DROP TABLE "person_contact_point"`);
        await queryRunner.query(`DROP TYPE "public"."person_contact_point_use_enum"`);
        await queryRunner.query(`DROP TABLE "person_name"`);
        await queryRunner.query(`DROP TYPE "public"."person_name_use_enum"`);
        await queryRunner.query(`ALTER TABLE "encounter" RENAME COLUMN "patientId" TO "subjectId"`);
        await queryRunner.query(`ALTER TABLE "encounter" RENAME COLUMN "subjectId" TO "patientId"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2bb6640ba6d3f27865b755873b" ON "appointment_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0cf84538504110d60bd43bf814" ON "encounter_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1ae0b84abc42f9f6c5d80cd2d7" ON "practitioner_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9fb6a84f8a0b0e80931c4c1d7c" ON "qualification_identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_750a348c49aae2866fdd08efbe" ON "identifier" ("system", "value") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7e6ca88c465709b8b77c69f125" ON "patient_identifier" ("system", "value") `);
        await queryRunner.query(`ALTER TABLE "encounter" ADD CONSTRAINT "FK_a9c05100cb3647a5660d1c4c20d" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_communication" ADD CONSTRAINT "FK_7027a305efdef9c31ed79c3c912" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_identifier" ADD CONSTRAINT "FK_933bf102d92916ab3f97c9878d2" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_address" ADD CONSTRAINT "FK_971744b316662409103fa145f87" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_contact_point" ADD CONSTRAINT "FK_d27a1a70421e51e5b93f292c118" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_name" ADD CONSTRAINT "FK_8d1b60aefc150fdd6c89d05eb4e" FOREIGN KEY ("patientId") REFERENCES "patient"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
